file = {
  "ahsm.lua", 
  "run.lua", 
  "tools/to_dot.lua", 
  "tools/run_to_dot.lua", 
  "tools/debug_plain.lua",
  "tools/cb_list.lua",
}
examples = {"examples/composite.lua", "examples/helloworld.lua", "examples/timeout_change.lua"}
project = "ahsm"
dir='doc/'
description = "A Hierarchical State Machine"
format = 'markdown'
--tool={"tools/to_dot.lua", "tools/run_to_dot.lua"}
readme = "README.md"

